spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/finance-manager
    username: ${DB_USER}
    password: ${DB_PASSWORD}

exchange:
  free-currency:
    api-key: ${FREE_CURRENCY_API_KEY}
  open-exchange:
    app-id: ${OPEN_EXCHANGE_APP_ID}
  exchange-rate:
    api-key: ${EXCHANGE_RATE_API_KEY}
  coin-gecko:
    api-key: ${COIN_GECKO_API_KEY}

ai:
  open-ai:
    api-key: ${OPEN_AI_API_KEY}